#! /usr/bin/zsh

pdflatex -halt-on-error report.tex  >> /dev/null
bibtex report >> /dev/null
pdflatex -halt-on-error report.tex  >> /dev/null
pdflatex -halt-on-error report.tex  >> /dev/null

mv report.pdf ../report.pdf
